version: '3.8'

services:
  apigateway:
    image: your-business-services-image:tag
    ports:
      - "8081:8080"
    networks:
      - microservices-network

  discovery:
    image: your-platform-services-image:tag
    ports:
      - "8082:8080"
    networks:
      - microservices-network

networks:
  microservices-network:

