version: '3.8'

services:
  foos-resources:
    build:
      context: ./apigateway/foos-resources
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - microservices-network

  uiapplication:
    build:
      context: ./apigateway/UIApplication
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - microservices-network

  eureka-server:
    build:
      context: ./discovery/eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  eureka-client:
    build:
      context: ./discovery/eureka-client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    environment:
      server.port: 8081
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  eureka-feign:
    build:
      context: ./discovery/eureka-feign
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    environment:
      server.port: 8082
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

networks:
  microservices-network:
    driver: bridge
